# gcloud beta builds import --source=<filename>
description: 'Kustomize Image Build: Push to ^master$ branch'
filename: kustomize/cloudbuild.yaml
includedFiles:
- kustomize/*
name: kustomize-image-build
github:
  name: cloud-builders-community
  owner: Friendr
  push:
    branch: ^master$
substitutions:
  _BUILD_DIRECTORY: kustomize
